//FINALLY

try {
    let a = 0
    console.log(program)
    console.log("program ran successsfully")
}
catch (err) {
    console.log("this is an error")
    console.log(p)
}
finally {
    console.log("this is finally this will get executed if it is present no matter it catches an errror or  not")
}